name: Debug CI

on:
  push:
    branches: [ main ]
    tags: [ d* ]

jobs:
  deploy:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.16.0]

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Install pods
        run: cd ios && pod install

      - name: Set environment variables from project settings
        run: |
          exec .github/scripts/set-env-from-xcodeproj.sh

      - name: Import signing certificate
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.DEBUG_SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.DEBUG_SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          exec .github/scripts/import-certificate.sh

      - name: Import provisioning profile
        env:
          PROVISIONING_PROFILE_DATA: ${{ secrets.DEBUG_PROVISIONING_PROFILE_DATA }}
        run: |
          exec .github/scripts/import-profile.sh

      - name: Build app
        run: |
          pwd
          cd ios
          fastlane run build_app workspace:"taroDemo.xcworkspace" configuration:"Debug" scheme:"taroDemo"
          cd ..

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build.log
          path: taroDemo/

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/d')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            taroDemo.ipa
            taroDemo.app.dSYM.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}